[profile.default]
solc_version = "0.8.24"         # 与 OZ v5 兼容（^0.8.20 以上即可）
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"